#![doc = "Peripheral access API for EFM32HG309F64 microcontrollers (generated using svd2rust v0.37.1 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.1/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_cfg))]
#[doc = r"Number available in the NVIC for configuring priority"]
pub const NVIC_PRIO_BITS: u8 = 3;
#[cfg(feature = "rt")]
pub use self::Interrupt as interrupt;
pub use cortex_m::peripheral::Peripherals as CorePeripherals;
pub use cortex_m::peripheral::{CBP, CPUID, DCB, DWT, FPB, ITM, MPU, NVIC, SCB, SYST, TPIU};
#[cfg(feature = "rt")]
pub use cortex_m_rt::interrupt;
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
extern "C" {
    fn DMA();
    fn GPIO_EVEN();
    fn TIMER0();
    fn ACMP0();
    fn ADC0();
    fn I2C0();
    fn GPIO_ODD();
    fn TIMER1();
    fn USART1_RX();
    fn USART1_TX();
    fn LEUART0();
    fn PCNT0();
    fn RTC();
    fn CMU();
    fn VCMP();
    fn MSC();
    fn AES();
    fn USART0_RX();
    fn USART0_TX();
    fn USB();
    fn TIMER2();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[link_section = ".vector_table.interrupts"]
#[no_mangle]
pub static __INTERRUPTS: [Vector; 21] = [
    Vector { _handler: DMA },
    Vector {
        _handler: GPIO_EVEN,
    },
    Vector { _handler: TIMER0 },
    Vector { _handler: ACMP0 },
    Vector { _handler: ADC0 },
    Vector { _handler: I2C0 },
    Vector { _handler: GPIO_ODD },
    Vector { _handler: TIMER1 },
    Vector {
        _handler: USART1_RX,
    },
    Vector {
        _handler: USART1_TX,
    },
    Vector { _handler: LEUART0 },
    Vector { _handler: PCNT0 },
    Vector { _handler: RTC },
    Vector { _handler: CMU },
    Vector { _handler: VCMP },
    Vector { _handler: MSC },
    Vector { _handler: AES },
    Vector {
        _handler: USART0_RX,
    },
    Vector {
        _handler: USART0_TX,
    },
    Vector { _handler: USB },
    Vector { _handler: TIMER2 },
];
#[doc = r"Enumeration of all the interrupts."]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "0 - DMA"]
    DMA = 0,
    #[doc = "1 - GPIO_EVEN"]
    GPIO_EVEN = 1,
    #[doc = "2 - TIMER0"]
    TIMER0 = 2,
    #[doc = "3 - ACMP0"]
    ACMP0 = 3,
    #[doc = "4 - ADC0"]
    ADC0 = 4,
    #[doc = "5 - I2C0"]
    I2C0 = 5,
    #[doc = "6 - GPIO_ODD"]
    GPIO_ODD = 6,
    #[doc = "7 - TIMER1"]
    TIMER1 = 7,
    #[doc = "8 - USART1_RX"]
    USART1_RX = 8,
    #[doc = "9 - USART1_TX"]
    USART1_TX = 9,
    #[doc = "10 - LEUART0"]
    LEUART0 = 10,
    #[doc = "11 - PCNT0"]
    PCNT0 = 11,
    #[doc = "12 - RTC"]
    RTC = 12,
    #[doc = "13 - CMU"]
    CMU = 13,
    #[doc = "14 - VCMP"]
    VCMP = 14,
    #[doc = "15 - MSC"]
    MSC = 15,
    #[doc = "16 - AES"]
    AES = 16,
    #[doc = "17 - USART0_RX"]
    USART0_RX = 17,
    #[doc = "18 - USART0_TX"]
    USART0_TX = 18,
    #[doc = "19 - USB"]
    USB = 19,
    #[doc = "20 - TIMER2"]
    TIMER2 = 20,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[doc = "AES"]
pub type Aes = crate::Periph<aes::RegisterBlock, 0x400e_0000>;
impl core::fmt::Debug for Aes {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Aes").finish()
    }
}
#[doc = "AES"]
pub mod aes;
#[doc = "DMA"]
pub type Dma = crate::Periph<dma::RegisterBlock, 0x400c_2000>;
impl core::fmt::Debug for Dma {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dma").finish()
    }
}
#[doc = "DMA"]
pub mod dma;
#[doc = "USB"]
pub type Usb = crate::Periph<usb::RegisterBlock, 0x400c_4000>;
impl core::fmt::Debug for Usb {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usb").finish()
    }
}
#[doc = "USB"]
pub mod usb;
#[doc = "MSC"]
pub type Msc = crate::Periph<msc::RegisterBlock, 0x400c_0000>;
impl core::fmt::Debug for Msc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Msc").finish()
    }
}
#[doc = "MSC"]
pub mod msc;
#[doc = "EMU"]
pub type Emu = crate::Periph<emu::RegisterBlock, 0x400c_6000>;
impl core::fmt::Debug for Emu {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Emu").finish()
    }
}
#[doc = "EMU"]
pub mod emu;
#[doc = "RMU"]
pub type Rmu = crate::Periph<rmu::RegisterBlock, 0x400c_a000>;
impl core::fmt::Debug for Rmu {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rmu").finish()
    }
}
#[doc = "RMU"]
pub mod rmu;
#[doc = "CMU"]
pub type Cmu = crate::Periph<cmu::RegisterBlock, 0x400c_8000>;
impl core::fmt::Debug for Cmu {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cmu").finish()
    }
}
#[doc = "CMU"]
pub mod cmu;
#[doc = "TIMER0"]
pub type Timer0 = crate::Periph<timer0::RegisterBlock, 0x4001_0000>;
impl core::fmt::Debug for Timer0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer0").finish()
    }
}
#[doc = "TIMER0"]
pub mod timer0;
#[doc = "TIMER1"]
pub type Timer1 = crate::Periph<timer1::RegisterBlock, 0x4001_0400>;
impl core::fmt::Debug for Timer1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer1").finish()
    }
}
#[doc = "TIMER1"]
pub mod timer1;
#[doc = "TIMER2"]
pub type Timer2 = crate::Periph<timer2::RegisterBlock, 0x4001_0800>;
impl core::fmt::Debug for Timer2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer2").finish()
    }
}
#[doc = "TIMER2"]
pub mod timer2;
#[doc = "ACMP0"]
pub type Acmp0 = crate::Periph<acmp0::RegisterBlock, 0x4000_1000>;
impl core::fmt::Debug for Acmp0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Acmp0").finish()
    }
}
#[doc = "ACMP0"]
pub mod acmp0;
#[doc = "USART0"]
pub type Usart0 = crate::Periph<usart0::RegisterBlock, 0x4000_c000>;
impl core::fmt::Debug for Usart0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usart0").finish()
    }
}
#[doc = "USART0"]
pub mod usart0;
#[doc = "USART1"]
pub type Usart1 = crate::Periph<usart1::RegisterBlock, 0x4000_c400>;
impl core::fmt::Debug for Usart1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usart1").finish()
    }
}
#[doc = "USART1"]
pub mod usart1;
#[doc = "PRS"]
pub type Prs = crate::Periph<prs::RegisterBlock, 0x400c_c000>;
impl core::fmt::Debug for Prs {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Prs").finish()
    }
}
#[doc = "PRS"]
pub mod prs;
#[doc = "IDAC0"]
pub type Idac0 = crate::Periph<idac0::RegisterBlock, 0x4000_4000>;
impl core::fmt::Debug for Idac0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Idac0").finish()
    }
}
#[doc = "IDAC0"]
pub mod idac0;
#[doc = "GPIO"]
pub type Gpio = crate::Periph<gpio::RegisterBlock, 0x4000_6000>;
impl core::fmt::Debug for Gpio {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpio").finish()
    }
}
#[doc = "GPIO"]
pub mod gpio;
#[doc = "VCMP"]
pub type Vcmp = crate::Periph<vcmp::RegisterBlock, 0x4000_0000>;
impl core::fmt::Debug for Vcmp {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Vcmp").finish()
    }
}
#[doc = "VCMP"]
pub mod vcmp;
#[doc = "ADC0"]
pub type Adc0 = crate::Periph<adc0::RegisterBlock, 0x4000_2000>;
impl core::fmt::Debug for Adc0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Adc0").finish()
    }
}
#[doc = "ADC0"]
pub mod adc0;
#[doc = "LEUART0"]
pub type Leuart0 = crate::Periph<leuart0::RegisterBlock, 0x4008_4000>;
impl core::fmt::Debug for Leuart0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Leuart0").finish()
    }
}
#[doc = "LEUART0"]
pub mod leuart0;
#[doc = "PCNT0"]
pub type Pcnt0 = crate::Periph<pcnt0::RegisterBlock, 0x4008_6000>;
impl core::fmt::Debug for Pcnt0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pcnt0").finish()
    }
}
#[doc = "PCNT0"]
pub mod pcnt0;
#[doc = "I2C0"]
pub type I2c0 = crate::Periph<i2c0::RegisterBlock, 0x4000_a000>;
impl core::fmt::Debug for I2c0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c0").finish()
    }
}
#[doc = "I2C0"]
pub mod i2c0;
#[doc = "RTC"]
pub type Rtc = crate::Periph<rtc::RegisterBlock, 0x4008_0000>;
impl core::fmt::Debug for Rtc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rtc").finish()
    }
}
#[doc = "RTC"]
pub mod rtc;
#[doc = "WDOG"]
pub type Wdog = crate::Periph<wdog::RegisterBlock, 0x4008_8000>;
impl core::fmt::Debug for Wdog {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Wdog").finish()
    }
}
#[doc = "WDOG"]
pub mod wdog;
#[doc = "MTB"]
pub type Mtb = crate::Periph<mtb::RegisterBlock, 0xf004_0000>;
impl core::fmt::Debug for Mtb {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Mtb").finish()
    }
}
#[doc = "MTB"]
pub mod mtb;
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "AES"]
    pub aes: Aes,
    #[doc = "DMA"]
    pub dma: Dma,
    #[doc = "USB"]
    pub usb: Usb,
    #[doc = "MSC"]
    pub msc: Msc,
    #[doc = "EMU"]
    pub emu: Emu,
    #[doc = "RMU"]
    pub rmu: Rmu,
    #[doc = "CMU"]
    pub cmu: Cmu,
    #[doc = "TIMER0"]
    pub timer0: Timer0,
    #[doc = "TIMER1"]
    pub timer1: Timer1,
    #[doc = "TIMER2"]
    pub timer2: Timer2,
    #[doc = "ACMP0"]
    pub acmp0: Acmp0,
    #[doc = "USART0"]
    pub usart0: Usart0,
    #[doc = "USART1"]
    pub usart1: Usart1,
    #[doc = "PRS"]
    pub prs: Prs,
    #[doc = "IDAC0"]
    pub idac0: Idac0,
    #[doc = "GPIO"]
    pub gpio: Gpio,
    #[doc = "VCMP"]
    pub vcmp: Vcmp,
    #[doc = "ADC0"]
    pub adc0: Adc0,
    #[doc = "LEUART0"]
    pub leuart0: Leuart0,
    #[doc = "PCNT0"]
    pub pcnt0: Pcnt0,
    #[doc = "I2C0"]
    pub i2c0: I2c0,
    #[doc = "RTC"]
    pub rtc: Rtc,
    #[doc = "WDOG"]
    pub wdog: Wdog,
    #[doc = "MTB"]
    pub mtb: Mtb,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            aes: Aes::steal(),
            dma: Dma::steal(),
            usb: Usb::steal(),
            msc: Msc::steal(),
            emu: Emu::steal(),
            rmu: Rmu::steal(),
            cmu: Cmu::steal(),
            timer0: Timer0::steal(),
            timer1: Timer1::steal(),
            timer2: Timer2::steal(),
            acmp0: Acmp0::steal(),
            usart0: Usart0::steal(),
            usart1: Usart1::steal(),
            prs: Prs::steal(),
            idac0: Idac0::steal(),
            gpio: Gpio::steal(),
            vcmp: Vcmp::steal(),
            adc0: Adc0::steal(),
            leuart0: Leuart0::steal(),
            pcnt0: Pcnt0::steal(),
            i2c0: I2c0::steal(),
            rtc: Rtc::steal(),
            wdog: Wdog::steal(),
            mtb: Mtb::steal(),
        }
    }
}
